source('~/Dropbox/My Mac (Wei’s MacBook Air)/Downloads/PhD-Coursework/22Spring/Econometrics/My_solution_to _hw/HW3/qderivfun.R', encoding = 'UTF-8')
source('~/Dropbox/My Mac (Wei’s MacBook Air)/Downloads/PhD-Coursework/22Spring/Econometrics/My_solution_to _hw/HW3/qderivfun2.R', encoding = 'UTF-8')
library(tidyverse)
attend<-read_csv("attend.csv")
attach(attend)
nlsout=nls(termgpa~(b0+b1*priGPA+b2*ACT),start=list(b0=1,b1=0.04321,b2=.9))
summary(nlsout)
thetahat=cbind(0.257753,0.875274,0.003514)
X=cbind(1,priGPA,ACT)
H=qderivfun2(as.matrix(termgpa),X,t(thetahat))